version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tech-challenge
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./src:/app/src
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres:15
    restart: always
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    ports:
      - 5432:5432