apiVersion: v1
kind: Secret
type: Opaque
metadata:
 name: aws-credentials
data: # FIXME: add actual credentials
  aws_secret_access_key: YXdzX3NlY3JldF9hY2Nlc3Nfa2V5
  aws_access_key: YXdzX2FjY2Vzc19rZXk=