apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: database
  name: database
  namespace: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      annotations:
      labels:
        app: database
    spec:
      containers:
          env: 
            - name: POSTGRES_USER
              value: compose-postgres
            - name: POSTGRES_PASSWORD
              value: compose-postgres
          image: postgres:15
          imagePullPolicy: IfNotPresent
          name: database
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          ports:
            - containerPort: 8080
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30

