Version: apps/v1
kind: Deployment
metadata:
  labels:
    app: database
  name: database
  namespace: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      annotations:
      labels:
        app: database
    spec:
      containers:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db:5432/compose-postgres
            - name: SPRING_DATASOURCE_USERNAME
              value: compose-postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: compose-postgres
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
          image: maven:3-amazoncorretto-17
          imagePullPolicy: IfNotPresent
          name: database
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          ports:
            - containerPort: 8080
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30

