apiVersion: v1
kind: Service
metadata:
  labels:
    app: database
  name: database
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: database
  sessionAffinity: None
  type: ClusterIP
